server:
 port: 7777

spring:
 application:
   name: hf-itheima-cloud-configServer

# 配置 链接git的相关信息
 cloud:
   config:
     server:
       git:
         uri: http://192.168.25.153:3000/root/config_server12.git
         username: root
         password: root

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://eureka01:7001/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ipAddress: 127.0.0.1
