server:
  port: 7001

eureka:
  instance:
#    hostname: 127.0.0.1 | www.itheima.com
    hostname: localhost
  server:
    enable-self-preservation: true  # 开发阶段false可以， 正式环境中建议启用自我保护模式
  client:
    register-with-eureka: false    # 不向服务端注册当前的服务
    fetch-registry: false           # server 端不需要获取对应的服务信息
    service-url:
#      defaultZone:   http://eureka02:7002/eureka/,http://eureka03:7003/eureka/    #设置eureka server的交互地址，即对外暴露的地址
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/    #设置eureka server的交互地址，即对外暴露的地址

#security:
#  basic:
#    enable: true #开启基于HTTP basic的认证
#  user: #配置用户的账号信息
#    name: itheima
#    password: itheima